name: CI/CD Pipeline for Java Web App

on:
  push:
    branches:
      - main
      - '*'
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Specify the Java version for your app
          distribution: oracle
          cache: maven

      - name: Run tests with Maven
        run: mvn test

  deploy_website:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Deploy the web
        run: |
          mvn clean install
          java -jar target/simple-website-1.0-SNAPSHOT.jar &

      - name: Verify deployment
        run: |
          response=$(curl --write-out "%{http_code}" --silent --output /dev/null http://localhost:8080/healthcheck)
          if [ "$response" -eq 200 ]; then
            echo "Webpage is up and running!"
          else
            echo "Webpage did not return status code 200. Response: $response"
            exit 1  # Fail the job if the status is not 200
          fi

  upload_to_docker_hub:
    runs-on: ubuntu-latest
    needs: deploy_website
    env:
      DOCKER_HUB_NAME: "colinwang847"
      DOCKER_HUB_APP: "reactapp"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./my-app
          push: true
          tags: ${{env.DOCKER_HUB_NAME}}/${{env.DOCKER_HUB_APP}}:${{ github.sha }}